site_name: XMPro Platform Documentation
site_url: https://docs.xmpro.com/
site_description: Documentation for the XMPro Intelligent Digital Twin Suite
repo_url: https://github.com/XMPro-Auto/xm-platform-docs
repo_name: xm-platform-docs
edit_uri: edit/main/docs/

theme:
  name: material
  logo: images/logo-light.png
  favicon: images/favicon.png
  font: false
  palette:
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.action.edit
    - toc.follow
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2025 XMPro. All rights reserved.

extra:
  version:
    provider: mike
    default: stable
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/XMPro-Auto
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/xmpro

plugins:
  - search
  - mike:
      alias_type: symlink
      canonical_version: null

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Browser Requirements: getting-started/browser-requirements.md
    - End-to-End Use Case: getting-started/end-to-end-use-case.md
  - Concepts:
    - Agent:
      - concepts/agent/index.md
      - Virtual vs Non-Virtual Agents: concepts/agent/virtual-vs-non-virtual-agents.md
      - Event-Level vs Agent-Level Streaming: concepts/agent/event-level-streaming-vs-agent-level-streaming.md
    - Application:
      - concepts/application/index.md
      - App Files: concepts/application/app-files.md
      - Block: concepts/application/block.md
      - Block Properties: concepts/application/block-properties.md
      - Block Styling: concepts/application/block-styling.md
      - Canvas: concepts/application/canvas.md
      - Data Integration: concepts/application/data-integration.md
      - Devices: concepts/application/devices.md
      - Flex: concepts/application/flex.md
      - Metablocks: concepts/application/metablocks.md
      - Navigation and Parameters: concepts/application/navigation-and-parameters.md
      - Page: concepts/application/page.md
      - Page Layers: concepts/application/page-layers.md
      - Template: concepts/application/template.md
      - Variables and Expressions: concepts/application/variables-and-expressions.md
    - Category: concepts/category.md
    - Collection and Stream Host: concepts/collection.md
    - Connector: concepts/connector.md
    - Data Stream:
      - concepts/data-stream/index.md
      - Running Data Streams: concepts/data-stream/running-data-streams.md
      - Stream Object Configuration: concepts/data-stream/stream-object-configuration.md
      - Timeline: concepts/data-stream/timeline.md
      - Verifying Stream Integrity: concepts/data-stream/verifying-stream-integrity.md
    - Insights:
      - Data Delivery Insights: concepts/insights/data-delivery-insights.md
    - Landing Pages and Favorites: concepts/landing-pages.md
    - Manage Access: concepts/manage-access.md
    - Recommendation:
      - concepts/recommendation/index.md
      - Action Requests: concepts/recommendation/action-requests.md
      - Auto Escalate: concepts/recommendation/auto-escalate.md
      - Deleted Items: concepts/recommendation/deleted-items.md
      - Execution Order: concepts/recommendation/execution-order.md
      - Form: concepts/recommendation/form.md
      - Notification: concepts/recommendation/notification.md
      - Recommendation Alert: concepts/recommendation/recommendation-alert.md
      - Recommendation Scoring: concepts/recommendation/recommendation-scoring.md
      - Rule: concepts/recommendation/rule.md
    - Variable: concepts/variable.md
    - Version: concepts/version.md
    - XMPro AI:
      - concepts/xmpro-ai/index.md
      - XMPro Notebook: concepts/xmpro-ai/xmpro-notebook.md
  - How-To Guides:
    - how-tos/index.md
    - Agents:
      - how-tos/agents/index.md
      - Building Agents: how-tos/agents/building-agents.md
      - Debugging an Agent: how-tos/agents/debugging-an-agent.md
      - Manage Agents: how-tos/agents/manage-agents.md
      - Packaging Agents: how-tos/agents/packaging-agents.md
    - Applications:
      - how-tos/apps/index.md
      - Check Connector Logs: how-tos/apps/check-connector-logs.md
      - Create and Maintain Notes: how-tos/apps/create-and-maintain-notes.md
      - Design Pages for Mobile: how-tos/apps/design-pages-for-mobile.md
      - Import an App Page: how-tos/apps/import-an-app-page.md
      - Manage App Files: how-tos/apps/manage-app-files.md
      - Manage Apps: how-tos/apps/manage-apps.md
      - Manage Connections: how-tos/apps/manage-connections.md
      - Manage Data Sources: how-tos/apps/manage-data-sources.md
      - Manage Pages: how-tos/apps/manage-pages.md
      - Manage Templates: how-tos/apps/manage-templates.md
      - Manage Themes: how-tos/apps/manage-themes.md
      - Manage Widgets: how-tos/apps/manage-widgets.md
      - Navigate Between Apps: how-tos/apps/navigate-between-apps.md
      - Navigate Between Pages: how-tos/apps/navigate-between-pages.md
      - Page Data: how-tos/apps/page-data.md
      - Pass Parameters Between Pages: how-tos/apps/pass-parameters-between-pages.md
      - Use Block Styling and Devices: how-tos/apps/use-block-styling-and-devices.md
      - Use Data Sources in the Page: how-tos/apps/use-data-sources-in-the-page.md
      - Use Dynamic Properties: how-tos/apps/use-dynamic-properties.md
      - Use Expression Properties: how-tos/apps/use-expression-properties.md
      - Use Flex: how-tos/apps/use-flex.md
      - Use Page Layers: how-tos/apps/use-page-layers.md
      - Use Validation: how-tos/apps/use-validation.md
      - Use Variables and Expressions: how-tos/apps/use-variables-and-expressions.md
    - Connectors:
      - how-tos/connectors/index.md
      - Building Connectors: how-tos/connectors/building-connectors.md
      - Manage Connectors: how-tos/connectors/manage-connectors.md
      - Packaging Connectors: how-tos/connectors/packaging-connectors.md
    - Data Streams:
      - how-tos/data-streams/index.md
      - Check Data Stream Logs: how-tos/data-streams/check-data-stream-logs.md
      - Context Menu: how-tos/data-streams/context-menu.md
      - Manage Collections: how-tos/data-streams/manage-collections.md
      - Manage Data Streams: how-tos/data-streams/manage-data-streams.md
      - Manage Recurrent Data Streams: how-tos/data-streams/manage-recurrent-data-streams.md
      - Remote Receivers and Publishers: how-tos/data-streams/remote-receivers-and-publishers.md
      - Run an Integrity Check: how-tos/data-streams/run-an-integrity-check.md
      - Setup Input Mappings: how-tos/data-streams/setup-input-mappings.md
      - Troubleshoot a Data Stream: how-tos/data-streams/troubleshoot-a-data-stream.md
      - Upgrade a Stream Object Version: how-tos/data-streams/upgrade-a-stream-object-version.md
      - Use Business Case and Notes: how-tos/data-streams/use-business-case-and-notes.md
      - Use Error Endpoints: how-tos/data-streams/use-error-endpoints.md
      - Use Live View: how-tos/data-streams/use-live-view.md
      - Use Stream Metrics: how-tos/data-streams/use-stream-metrics.md
      - Use the Timeline: how-tos/data-streams/use-the-timeline.md
    - Import, Export, and Clone: how-tos/import-export-and-clone.md
    - Manage Access: how-tos/manage-access.md
    - Manage Categories: how-tos/manage-categories.md
    - Manage Landing Pages: how-tos/manage-landing-pages.md
    - Manage Site Settings: how-tos/manage-site-settings.md
    - Manage Variables: how-tos/manage-variables.md
    - Manage Versions: how-tos/manage-versions.md
    - Publish:
      - how-tos/publish/index.md
      - Admin Unpublish Override: how-tos/publish/admin-unpublish-override.md
    - Recommendations:
      - how-tos/recommendations/index.md
      - Create Rules: how-tos/recommendations/create-rules.md
      - Manage Alerts: how-tos/recommendations/manage-alerts.md
      - Manage Alerts on Mobile: how-tos/recommendations/manage-alerts-on-mobile.md
      - Manage Categories: how-tos/recommendations/manage-categories.md
      - Manage Deleted Recommendation Items: how-tos/recommendations/manage-deleted-recommendation-items.md
      - Manage Forms: how-tos/recommendations/manage-forms.md
      - Manage Notifications: how-tos/recommendations/manage-notifications.md
      - Manage Notification Templates: how-tos/recommendations/manage-notification-templates.md
      - Manage Recommendations: how-tos/recommendations/manage-recommendations.md
      - Manage Variables: how-tos/recommendations/manage-variables.md
      - Subscribe to Notifications: how-tos/recommendations/subscribe-to-notifications.md
    - Stream Host: how-tos/stream-host.md
  - Blocks:
    - blocks-toolbox/index.md
    - Common Properties: blocks-toolbox/common-properties.md
    - Actions:
      - blocks-toolbox/actions/index.md
      - Box Hyperlink: blocks-toolbox/actions/box-hyperlink.md
      - Button: blocks-toolbox/actions/button.md
      - Data Operations: blocks-toolbox/actions/data-operations.md
      - Hyperlink: blocks-toolbox/actions/hyperlink.md
    - Advanced:
      - blocks-toolbox/advanced/index.md
      - Metablock: blocks-toolbox/advanced/metablock.md
    - AI:
      - blocks-toolbox/ai/index.md
      - Azure Copilot: blocks-toolbox/ai/azure-copilot.md
      - ChatGPT Copilot: blocks-toolbox/ai/chatgpt-copilot.md
    - Basic:
      - blocks-toolbox/basic/index.md
      - Calendar: blocks-toolbox/basic/calendar.md
      - Checkbox: blocks-toolbox/basic/checkbox.md
      - Color Selector: blocks-toolbox/basic/color-selector.md
      - Data Grid: blocks-toolbox/basic/data-grid.md
      - Date Selector: blocks-toolbox/basic/date-selector.md
      - Dropdown Grid: blocks-toolbox/basic/dropdown-grid.md
      - Embedded Page: blocks-toolbox/basic/embedded-page.md
      - File Library: blocks-toolbox/basic/file-library.md
      - File Uploader: blocks-toolbox/basic/file-uploader.md
      - HTML Editor: blocks-toolbox/basic/html-editor.md
      - Image: blocks-toolbox/basic/image.md
      - Indicator: blocks-toolbox/basic/indicator.md
      - List: blocks-toolbox/basic/list.md
      - Lookup: blocks-toolbox/basic/lookup.md
      - Number Selector: blocks-toolbox/basic/number-selector.md
      - Radio Buttons: blocks-toolbox/basic/radio-buttons.md
      - Range Selector: blocks-toolbox/basic/range-selector.md
      - Select Box: blocks-toolbox/basic/select-box.md
      - Switch: blocks-toolbox/basic/switch.md
      - Tags: blocks-toolbox/basic/tags.md
      - Text: blocks-toolbox/basic/text.md
      - Text Area: blocks-toolbox/basic/text-area.md
      - Textbox: blocks-toolbox/basic/textbox.md
      - Tree Grid: blocks-toolbox/basic/tree-grid.md
      - Tree List: blocks-toolbox/basic/tree-list.md
    - Device Input:
      - blocks-toolbox/device-input/index.md
      - Location Capture: blocks-toolbox/device-input/location-capture.md
      - Visual Media Capture: blocks-toolbox/device-input/visual-media-capture.md
    - Layout:
      - blocks-toolbox/layout/index.md
      - Accordion: blocks-toolbox/layout/accordion.md
      - Box and Data Repeater Box: blocks-toolbox/layout/box-and-data-repeater-box.md
      - Card and Content Card: blocks-toolbox/layout/card-and-content-card.md
      - Field and Fieldset: blocks-toolbox/layout/field-and-fieldset.md
      - Horizontal and Vertical Stacked Layouts: blocks-toolbox/layout/horizontal-and-vertical-stacked-layouts.md
      - Layout Grid: blocks-toolbox/layout/layout-grid.md
      - Menu: blocks-toolbox/layout/menu.md
      - Scroll Box: blocks-toolbox/layout/scroll-box.md
      - Tabs: blocks-toolbox/layout/tabs.md
      - Templated List: blocks-toolbox/layout/templated-list.md
      - Toolbar: blocks-toolbox/layout/toolbar.md
    - Recommendations:
      - blocks-toolbox/recommendations/index.md
      - Alert Action: blocks-toolbox/recommendations/alert-action.md
      - Alert Event Data: blocks-toolbox/recommendations/alert-event-data.md
      - Alert Form: blocks-toolbox/recommendations/alert-form.md
      - Alert List: blocks-toolbox/recommendations/alert-list.md
      - Alert Survey: blocks-toolbox/recommendations/alert-survey.md
      - Alert Timeline: blocks-toolbox/recommendations/alert-timeline.md
      - Alert Triage: blocks-toolbox/recommendations/alert-triage.md
      - Recommendation Alert Discussion: blocks-toolbox/recommendations/recommendation-alert-discussion.md
      - Recommendation Analytics: blocks-toolbox/recommendations/recommendation-analytics.md
      - Recommendation Chart: blocks-toolbox/recommendations/recommendation-chart.md
    - Visualizations:
      - blocks-toolbox/visualizations/index.md
      - Autodesk Forge: blocks-toolbox/visualizations/autodesk-forge.md
      - Autodesk Forge (Legacy): blocks-toolbox/visualizations/autodesk-forge-1.md
      - Azure Digital Twin Hierarchy: blocks-toolbox/visualizations/azure-digital-twin-hierarchy.md
      - Bar Gauge: blocks-toolbox/visualizations/bar-gauge.md
      - Chart: blocks-toolbox/visualizations/chart.md
      - Circular Gauge: blocks-toolbox/visualizations/circular-gauge.md
      - D3 Visualization: blocks-toolbox/visualizations/d3-visualization.md
      - Esri Map: blocks-toolbox/visualizations/esri-map.md
      - Image Map: blocks-toolbox/visualizations/image-map.md
      - Linear Gauge: blocks-toolbox/visualizations/linear-gauge.md
      - Map: blocks-toolbox/visualizations/map.md
      - Pie Chart: blocks-toolbox/visualizations/pie-chart.md
      - Pivot Grid: blocks-toolbox/visualizations/pivot-grid.md
      - Polar Chart: blocks-toolbox/visualizations/polar-chart.md
      - Power BI: blocks-toolbox/visualizations/power-bi.md
      - Sparkline: blocks-toolbox/visualizations/sparkline.md
      - Time Series Analysis: blocks-toolbox/visualizations/time-series-analysis.md
      - Tree Map: blocks-toolbox/visualizations/tree-map.md
      - Unity: blocks-toolbox/visualizations/unity.md
      - Unity (Legacy): blocks-toolbox/visualizations/unity-1.md
    - Widgets: blocks-toolbox/widgets.md
  - Administration:
    - Administrative Accounts: administration/administrative-accounts.md
    - Companies:
      - administration/companies/index.md
      - Manage a Company: administration/companies/manage-a-company.md
      - Manage Company Subscriptions: administration/companies/manage-company-subscriptions.md
      - Manage License: administration/companies/manage-license.md
      - Register a Company: administration/companies/register-a-company.md
    - Language: administration/language.md
    - Subscriptions:
      - administration/subscriptions-admin/index.md
      - Manage User Access: administration/subscriptions-admin/manage-user-access.md
      - Request and Apply a License: administration/subscriptions-admin/request-and-apply-a-license.md
      - Setup Auto Approvals: administration/subscriptions-admin/setup-auto-approvals-default-subscriptions.md
    - Users:
      - administration/users/index.md
      - Business Role for a User: administration/users/business-role-for-a-user.md
      - Change Password: administration/users/change-password.md
      - Delete a User: administration/users/delete-a-user.md
      - Invite a User: administration/users/invite-a-user.md
      - Profile: administration/users/profile.md
      - Register an Account: administration/users/register-an-account.md
      - Reset Password: administration/users/reset-password.md
  - Deployment:
    - Overview: installation/overview.md
    - installation/index.md
    - Install: installation/install.md
    - Azure Terraform Preparation: installation/azure-terraform-preparation.md
    - Deploy XMPro:
      - installation/deployment/index.md
      - Azure Terraform:
        - installation/deployment/azure-terraform/index.md
        - Advanced Configuration: installation/deployment/azure-terraform/advanced-configuration.md
        - Azure Sizing: installation/deployment/azure-terraform/azure-sizing.md
        - Implementation Guide: installation/deployment/azure-terraform/implementation-guide.md
        - Troubleshooting: installation/deployment/azure-terraform/troubleshooting.md
      - Windows Server 2022:
        - installation/deployment/windows-server-2022/index.md
        - Airgapped Deployment: installation/deployment/windows-server-2022/airgapped-deployment.md
        - Multi-Server Deployment: installation/deployment/windows-server-2022/multi-server-deployment.md
        - Troubleshooting: installation/deployment/windows-server-2022/troubleshooting.md
    - Post-Deployment:
      - installation/complete-installation/index.md
      - Deploy Stream Connector Infrastructure: installation/complete-installation/deploy-stream-connector-infrastructure.md
      - Install Connectors: installation/complete-installation/install-connectors.md
      - Set Up a Tenant Company: installation/complete-installation/set-up-a-tenant-company.md
      - Install Stream Host:
        - installation/complete-installation/install-stream-host/index.md
        - Azure Terraform: installation/complete-installation/install-stream-host/azure-terraform.md
        - Docker: installation/complete-installation/install-stream-host/docker.md
        - Windows x64: installation/complete-installation/install-stream-host/windows-x64.md
  - Technical Reference:
    - Health Checks: technical-reference/health-checks.md
    - Mosquitto MQTT Broker: technical-reference/mosquitto-mqtt-broker.md
    - OAuth SMTP Configuration: technical-reference/oauth-smtp-configuration.md
    - Redis Cache Implementation: technical-reference/redis-cache-implementation.md
    - SSO ADFS: technical-reference/sso-adfs.md
    - SSO Azure AD: technical-reference/sso-azure-ad.md
    - XMPro Log Events:
      - technical-reference/xmpro-log-events/index.md
      - AI Log Events: technical-reference/xmpro-log-events/ai-log-events.md
      - App Designer Log Events: technical-reference/xmpro-log-events/app-designer-log-events.md
      - Data Stream Designer Log Events: technical-reference/xmpro-log-events/data-stream-designer-log-events.md
      - Stream Host Log Events: technical-reference/xmpro-log-events/stream-host-log-events.md
      - Subscription Manager Log Events: technical-reference/xmpro-log-events/subscription-manager-log-events.md
  - Resources:
    - Icon Library: resources/icon-library.md
    - Platform Security: resources/platform-security.md
    - Sizing Guideline: resources/sizing-guideline.md
    - Container Scan: resources/container-scan-4-6-0.md
    - Practice Notes:
      - resources/practice-notes/index.md
      - Performant Landing Pages: resources/practice-notes/performant-landing-pages-in-real-time-monitoring.md
      - Unified Recommendation Alert Management: resources/practice-notes/unified-recommendation-alert-management.md
    - FAQs:
      - resources/faqs/index.md
      - Agent FAQs: resources/faqs/agent-faqs.md
      - Configuration: resources/faqs/configuration.md
      - General: resources/faqs/general.md
      - Implementation: resources/faqs/implementation.md
  - Release Notes: release-notes/index.md
